# System services
$hostFiles = ~/.config/scripts/firefox/host-files.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /home/sujat/.local/bin/optmization

# Clipboard management
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Custom scripts
exec-once = $hostFiles
