services:
  etal-frontend:
    #command : NODE_ENV=production npm run start
    image: sujatahmed/etal-frontend

    env_file:
      - frontend.env
    ports:
      - "5173:5173"
  etal-backend:

    image: sujatahmed/etal-backend
    #container_name: etal-backend
    env_file:
      - backend.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage  # Bind mount to host directory

  mongo:
    image: mongo:8.0.8
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "none"
    attach: false

volumes:
  mongodb-data:
