# Application launchers
bind = $mainMod, B, exec, $windows-switcher
bind = SUPER, Z, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind = ALT, B, exec, $browser
bind = ALT, M, exec, $menu
bind = ALT, T, exec, $terminal

