$mainMod = SUPER

bind = $mainMod, C, killactive
bind = $mainMod, M, exit
bind = $mainMod, V, togglefloating
bind = $mainMod, P, pseudo
bind = $mainMod, T, togglesplit
bind = $mainMod, F, fullscreen, 1

bindm = $mainMod, mouse:272, movewindow
bindm = SUPER_CTRL, mouse:272, resizewindow
