# Volume controls
$volume-up = pactl set-sink-volume @DEFAULT_SINK@ +3125
$volume-down = pactl set-sink-volume @DEFAULT_SINK@ -3125

bind = CTRL, up, exec, $volume-up
bind = CTRL, down, exec, $volume-down

# Brightness controls
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5% 
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Lock and power
bind = ALT SHIFT, L, exec, $lock
