# Focus movement
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, TAB, cyclenext
bind = $mainMod SHIFT, TAB, cyclenext, prev

# Window swapping
bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Window resizing
bind = $mainMod CTRL, L, resizeactive, 40 0
bind = $mainMod CTRL, H, resizeactive, -40 0
bind = $mainMod CTRL, K, resizeactive, 0 -40 
bind = $mainMod CTRL, J, resizeactive, 0 40

# Application launchers
bind = $mainMod, B, exec, $windows-switcher
bind = SUPER, Z, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind = ALT, B, exec, $browser
bind = ALT, M, exec, $menu
bind = ALT, T, exec, $terminal
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
