# Source all configuration files
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/gestures.conf
source = ~/.config/hypr/config/rules.conf

# Source bindings
source = ~/.config/hypr/config/binds/main.conf
source = ~/.config/hypr/config/binds/navigation.conf
source = ~/.config/hypr/config/binds/workspace.conf
source = ~/.config/hypr/config/binds/media.conf

# Source exec commands
source = ~/.config/hypr/config/exec/autostart.conf
source = ~/.config/hypr/config/exec/services.conf

monitor=,highres,auto,1
