general {
    gaps_in = 6
    gaps_out = 15
    border_size = 4
    col.active_border = rgba(ffe4b5ff) rgba(ffe4b5ff) 45deg;
    col.inactive_border = rgba(595959ee)
    layout = scrolling
    allow_tearing = false
}

decoration {
    rounding = 5
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}
